package com.fsd.webserver.teamproject.teamProject.domain;

import java.math.BigDecimal;
import java.time.LocalDate;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.ID
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.Title
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.Director
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    private String director;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.ReleaseDate
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    private LocalDate releasedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.Genre
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    private String genre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.Rating
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    private BigDecimal rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.imgURL
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.ID
     *
     * @return the value of movies.ID
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.ID
     *
     * @param id the value for movies.ID
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.Title
     *
     * @return the value of movies.Title
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.Title
     *
     * @param title the value for movies.Title
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.Director
     *
     * @return the value of movies.Director
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.Director
     *
     * @param director the value for movies.Director
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.ReleaseDate
     *
     * @return the value of movies.ReleaseDate
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public LocalDate getReleasedate() {
        return releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.ReleaseDate
     *
     * @param releasedate the value for movies.ReleaseDate
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public void setReleasedate(LocalDate releasedate) {
        this.releasedate = releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.Genre
     *
     * @return the value of movies.Genre
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public String getGenre() {
        return genre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.Genre
     *
     * @param genre the value for movies.Genre
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public void setGenre(String genre) {
        this.genre = genre == null ? null : genre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.Rating
     *
     * @return the value of movies.Rating
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public BigDecimal getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.Rating
     *
     * @param rating the value for movies.Rating
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public void setRating(BigDecimal rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.imgURL
     *
     * @return the value of movies.imgURL
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.imgURL
     *
     * @param imgurl the value for movies.imgURL
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }
}