package com.fsd.webserver.teamproject.teamProject.mapper;

import java.util.List;

import com.fsd.webserver.teamproject.teamProject.domain.Movie;
import com.fsd.webserver.teamproject.teamProject.domain.MovieExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    long countByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    int deleteByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    int insert(Movie row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    int insertSelective(Movie row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
//    List<Movie> selectByExampleWithBLOBs(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    List<Movie> selectByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    Movie selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    int updateByExampleSelective(@Param("row") Movie row, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
//    int updateByExampleWithBLOBs(@Param("row") Movie row, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    int updateByExample(@Param("row") Movie row, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    int updateByPrimaryKeySelective(Movie row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
//    int updateByPrimaryKeyWithBLOBs(Movie row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Wed Oct 04 23:06:34 EDT 2023
     */
    int updateByPrimaryKey(Movie row);
}